name: Vitest

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Change Submodule URL to HTTPS
        run: |
          git config submodule.lexical.url https://github.com/piotrlewalski/lexical.git
          git submodule update --init --recursive
      - name: Install Dependencies
        run: |
          git submodule update --init --recursive
          npm install
      - name: Run Vitest
        run: |
          npm run test-unit
